// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/ratelimit.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReduceResponse_Status int32

const (
	ReduceResponse_UNKNOWN ReduceResponse_Status = 0
	ReduceResponse_ERROR   ReduceResponse_Status = 1
	ReduceResponse_OK      ReduceResponse_Status = 2
	ReduceResponse_NG      ReduceResponse_Status = 3
)

var ReduceResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "ERROR",
	2: "OK",
	3: "NG",
}
var ReduceResponse_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"ERROR":   1,
	"OK":      2,
	"NG":      3,
}

func (x ReduceResponse_Status) String() string {
	return proto.EnumName(ReduceResponse_Status_name, int32(x))
}
func (ReduceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_46549fea52d5c933, []int{1, 0}
}

type ReduceRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	MaxAmount            uint32   `protobuf:"varint,2,opt,name=maxAmount" json:"maxAmount,omitempty"`
	RefillAmount         uint32   `protobuf:"varint,3,opt,name=refillAmount" json:"refillAmount,omitempty"`
	RefillDurationSec    uint32   `protobuf:"varint,4,opt,name=refillDurationSec" json:"refillDurationSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceRequest) Reset()         { *m = ReduceRequest{} }
func (m *ReduceRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceRequest) ProtoMessage()    {}
func (*ReduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_46549fea52d5c933, []int{0}
}
func (m *ReduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceRequest.Unmarshal(m, b)
}
func (m *ReduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceRequest.Marshal(b, m, deterministic)
}
func (dst *ReduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceRequest.Merge(dst, src)
}
func (m *ReduceRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceRequest.Size(m)
}
func (m *ReduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceRequest proto.InternalMessageInfo

func (m *ReduceRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReduceRequest) GetMaxAmount() uint32 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *ReduceRequest) GetRefillAmount() uint32 {
	if m != nil {
		return m.RefillAmount
	}
	return 0
}

func (m *ReduceRequest) GetRefillDurationSec() uint32 {
	if m != nil {
		return m.RefillDurationSec
	}
	return 0
}

type ReduceResponse struct {
	Status               ReduceResponse_Status `protobuf:"varint,1,opt,name=status,enum=pkg.proto.ReduceResponse_Status" json:"status,omitempty"`
	Remaining            uint32                `protobuf:"varint,2,opt,name=remaining" json:"remaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReduceResponse) Reset()         { *m = ReduceResponse{} }
func (m *ReduceResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceResponse) ProtoMessage()    {}
func (*ReduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ratelimit_46549fea52d5c933, []int{1}
}
func (m *ReduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceResponse.Unmarshal(m, b)
}
func (m *ReduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceResponse.Marshal(b, m, deterministic)
}
func (dst *ReduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceResponse.Merge(dst, src)
}
func (m *ReduceResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceResponse.Size(m)
}
func (m *ReduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceResponse proto.InternalMessageInfo

func (m *ReduceResponse) GetStatus() ReduceResponse_Status {
	if m != nil {
		return m.Status
	}
	return ReduceResponse_UNKNOWN
}

func (m *ReduceResponse) GetRemaining() uint32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func init() {
	proto.RegisterType((*ReduceRequest)(nil), "pkg.proto.ReduceRequest")
	proto.RegisterType((*ReduceResponse)(nil), "pkg.proto.ReduceResponse")
	proto.RegisterEnum("pkg.proto.ReduceResponse_Status", ReduceResponse_Status_name, ReduceResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RateLimitService service

type RateLimitServiceClient interface {
	Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error)
}

type rateLimitServiceClient struct {
	cc *grpc.ClientConn
}

func NewRateLimitServiceClient(cc *grpc.ClientConn) RateLimitServiceClient {
	return &rateLimitServiceClient{cc}
}

func (c *rateLimitServiceClient) Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error) {
	out := new(ReduceResponse)
	err := grpc.Invoke(ctx, "/pkg.proto.RateLimitService/Reduce", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RateLimitService service

type RateLimitServiceServer interface {
	Reduce(context.Context, *ReduceRequest) (*ReduceResponse, error)
}

func RegisterRateLimitServiceServer(s *grpc.Server, srv RateLimitServiceServer) {
	s.RegisterService(&_RateLimitService_serviceDesc, srv)
}

func _RateLimitService_Reduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitServiceServer).Reduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.proto.RateLimitService/Reduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitServiceServer).Reduce(ctx, req.(*ReduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RateLimitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.RateLimitService",
	HandlerType: (*RateLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reduce",
			Handler:    _RateLimitService_Reduce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ratelimit.proto",
}

func init() {
	proto.RegisterFile("pkg/proto/ratelimit.proto", fileDescriptor_ratelimit_46549fea52d5c933)
}

var fileDescriptor_ratelimit_46549fea52d5c933 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0x86, 0x06, 0xe5, 0xa0, 0x95, 0xf1, 0x94, 0x22, 0x86, 0x28, 0x53, 0x07, 0x94,
	0xa2, 0xb2, 0xb0, 0x21, 0x10, 0x88, 0xa1, 0x28, 0x91, 0x1c, 0x21, 0x24, 0x36, 0x13, 0x8e, 0xc8,
	0xca, 0x27, 0x8e, 0x83, 0x60, 0xe3, 0x2f, 0xb0, 0xf2, 0x6b, 0x51, 0x9c, 0xb6, 0xa8, 0x02, 0x26,
	0xbf, 0xf7, 0xde, 0x33, 0x3c, 0x3e, 0x98, 0xd6, 0x59, 0x3a, 0xaf, 0x55, 0xa5, 0xab, 0xb9, 0x12,
	0x1a, 0x73, 0x59, 0x48, 0x1d, 0x98, 0x99, 0x39, 0x75, 0x96, 0xf6, 0xd1, 0xff, 0x24, 0x30, 0xe6,
	0xf8, 0xd4, 0x26, 0xc8, 0xf1, 0xa5, 0xc5, 0x46, 0x33, 0x0a, 0x56, 0x86, 0xef, 0x2e, 0xf1, 0xc8,
	0xcc, 0xe1, 0x5d, 0x64, 0x47, 0xe0, 0x14, 0xe2, 0xed, 0xa2, 0xa8, 0xda, 0x52, 0xbb, 0x43, 0x8f,
	0xcc, 0xc6, 0xfc, 0xa7, 0x60, 0x3e, 0xec, 0x2b, 0x7c, 0x96, 0x79, 0xbe, 0x02, 0x2c, 0x03, 0x6c,
	0x75, 0xec, 0x18, 0x0e, 0xfa, 0xf9, 0xaa, 0x55, 0x42, 0xcb, 0xaa, 0x8c, 0x31, 0x71, 0x77, 0x0c,
	0xf8, 0x7b, 0xe1, 0x7f, 0x11, 0x98, 0xac, 0x9d, 0x9a, 0xba, 0x2a, 0x1b, 0x64, 0x67, 0x60, 0x37,
	0x5a, 0xe8, 0xb6, 0x31, 0x5e, 0x93, 0x85, 0x17, 0x6c, 0xbe, 0x10, 0x6c, 0xa3, 0x41, 0x6c, 0x38,
	0xbe, 0xe2, 0x3b, 0x79, 0x85, 0x85, 0x90, 0xa5, 0x2c, 0xd3, 0xb5, 0xfc, 0xa6, 0xf0, 0x4f, 0xc0,
	0xee, 0x79, 0xb6, 0x07, 0xbb, 0x77, 0xe1, 0x32, 0x8c, 0xee, 0x43, 0x3a, 0x60, 0x0e, 0x8c, 0xae,
	0x39, 0x8f, 0x38, 0x25, 0xcc, 0x86, 0x61, 0xb4, 0xa4, 0xc3, 0xee, 0x0d, 0x6f, 0xa8, 0xb5, 0x88,
	0x81, 0x72, 0xa1, 0xf1, 0xb6, 0x3b, 0x67, 0x8c, 0xea, 0x55, 0x26, 0xc8, 0xce, 0xc1, 0xee, 0x25,
	0x98, 0xfb, 0x87, 0x97, 0x39, 0xeb, 0xe1, 0xf4, 0x5f, 0x63, 0x7f, 0x70, 0x09, 0x0f, 0x23, 0xb3,
	0xf9, 0x20, 0xe4, 0xd1, 0x36, 0xe9, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xfb, 0xca, 0x09,
	0xc0, 0x01, 0x00, 0x00,
}
